dataset_path: "data/client3_combined"
train_csv: "train_split.csv"
val_csv: "val_split.csv"
image_size: 384
local_epochs: 1
batch_size: 8
lr: 1e-4
weight_decay: 1e-5
num_classes: 8
is_regression: false

